linters:
  ElsePlacement:
    enabled: false
  HexLength:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  TrailingZero:
    enabled: true
  ZeroUnit:
    enabled: false
